version: 2
jobs:
  build:
    docker:
      - image: docker:18.01.0-ce-git
    working_directory: /tmp/src/fitlins
    steps:
      - run:
          name: Install parallel gzip and Python 3
          command: |
            apk add --no-cache pigz python3
      - checkout
      - setup_remote_docker
      - run:
          name: Fetch latest release image
          no_output_timeout: 10m
          command: |
            docker pull poldracklab/fitlins:latest
      - run:
          name: Build image
          no_output_timeout: 30m
          command: |
            THISVERSION=$( python3 -c 'import fitlins; print(fitlins.__version__)' )
            echo "Building version ${CIRCLE_TAG:-$THISVERSION}"
            docker build \
              --cache-from=poldracklab/fitlins \
              --rm=false \
              --tag poldracklab/fitlins:latest \
              --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
              --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
              --build-arg VERSION="${CIRCLE_TAG:-$THISVERSION}" .
      - run:
          name: Verify executable can be run
          command: docker run --rm poldracklab/fitlins:latest --help
      - run:
          name: Check version
          command: |
            THISVERSION=$( python3 -c 'import fitlins; print(fitlins.__version__)' )
            THISVERSION="${CIRCLE_TAG:-$THISVERSION}"
            DOCKERVERSION=$(docker run --rm poldracklab/fitlins:latest --version \
                           | tail -n 1 | sed -e 's/.*fit/fit/' -e 's/[\r\n]//g')
            echo "$THISVERSION"
            echo "$DOCKERVERSION"
            test "$DOCKERVERSION" = "fitlins v$THISVERSION"
      - run:
          name: Docker save
          no_output_timeout: 40m
          command: |
            mkdir -p /tmp/cache
            docker save poldracklab/fitlins:latest \
            | pigz -2 -p 3 > /tmp/cache/docker.tar.gz
      - persist_to_workspace:
          root: /tmp
          paths:
            - src/fitlins
      - save_cache:
          key: docker-v0-{{ .Branch }}-{{ .Revision }}-{{ epoch }}
          paths:
            - /tmp/cache/docker.tar.gz

  cache_test_data:
    docker:
      - image: markiewicz/datalad:0.0.1
    working_directory: /tmp/data
    steps:
      - checkout:
          path: /tmp/src
      - restore_cache:
          keys:
            - ds003-v0-{{ .Branch }}-
            - ds003-v0-master-
            - ds003-v0-
      - run:
          name: Set git ID
          command: |
            git config --global user.name 'FitLins CircleCI User'
            git config --global user.email 'crn.poldracklab@gmail.com'
      - run:
          name: Install fMRIPrep derivatives of ds000003
          command: |
            datalad install -r ///labs/poldrack/ds003_fmriprep
            datalad update ds003_fmriprep/
            datalad get ds003_fmriprep/sub-0{1,2,3}/func/*_space-MNI152NLin2009cAsym_desc-*.nii.gz \
                        ds003_fmriprep/sub-0{1,2,3}/func/*_desc-confounds_*.tsv \
                        ds003_fmriprep/dataset_description.json \
                        ds003_fmriprep/sub-*/*/*.json
      - run:
          name: Download a model for ds000003
          command: |
              mkdir -p ds003_models
              cp /tmp/src/examples/models/ds000003/models/model-001_smdl.json ds003_models/
      - save_cache:
         key: ds003-v0-{{ .Branch }}-{{ .BuildNum }}
         paths:
            - /tmp/data

  build_docs:
    docker:
      - image: python:3.7.4
    working_directory: /tmp/src/fitlins
    steps:
      - run:
          name: Check Python version and upgrade pip
          command: |
            python --version
            python -m pip install -U pip setuptools
      - run:
          name: Install pandoc
          command: |
            apt-get update
            apt-get install -y pandoc
      - checkout
      - run:
          name: Install FitLins
          command: |
            python -m pip install ".[docs]"
      - run:
          name: Build docs
          command: |
            make html
      - store_artifacts:
          path: /tmp/src/fitlins/docs/_build/html

  test_pytest:
    machine:
      image: circleci/classic:201711-01
    working_directory: /tmp/src/fitlins
    steps:
      - attach_workspace:
          at: /tmp
      - restore_cache:
          keys:
            - docker-v0-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Load Docker image layer cache
          no_output_timeout: 30m
          command: |
            docker info
            set +o pipefail
            if [ -f /tmp/cache/docker.tar.gz ]; then
              sudo apt update && sudo apt -y install pigz
              pigz -d --stdout /tmp/cache/docker.tar.gz | docker load
              docker images
            fi
      - run:
          name: Run pytest
          command: |
            mkdir -p /tmp/pytestcov
            chmod 777 /tmp/pytestcov
            docker run -v /tmp/pytestcov:/scratch \
              -e COVERAGE_FILE=/scratch/.coverage.pytest \
              --entrypoint="/neurodocker/startup.sh" \
              poldracklab/fitlins:latest \
              pytest --cov=fitlins /src/fitlins
      - persist_to_workspace:
          root: /tmp/pytestcov
          paths:
            - .coverage*

  test_ds003:
    machine:
      image: circleci/classic:201711-01
    working_directory: /tmp/src/fitlins
    steps:
      - attach_workspace:
          at: /tmp
      - restore_cache:
          keys:
            - docker-v0-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          keys:
            - ds003-v0-{{ .Branch }}-
            - ds003-v0-master-
            - ds003-v0-
      - run:
          name: Load Docker image layer cache
          no_output_timeout: 30m
          command: |
            docker info
            set +o pipefail
            if [ -f /tmp/cache/docker.tar.gz ]; then
              sudo apt update && sudo apt -y install pigz
              pigz -d --stdout /tmp/cache/docker.tar.gz | docker load
              docker images
            fi
      - run:
          name: Run FitLins
          no_output_timeout: 2h
          command: |
            mkdir -p /tmp/ds003/work /tmp/ds003/derivatives
            chmod 777 /tmp/ds003/work /tmp/ds003/derivatives
            export CONDA_PREFIX=/opt/miniconda-latest/envs/neuro
            docker run --rm -v /tmp/data/ds003_fmriprep:/data:ro \
                -v /tmp/ds003/derivatives:/out \
                -v /tmp/ds003/work:/scratch \
                -v /tmp/data/ds003_models:/models \
                -e COVERAGE_FILE=/scratch/.coverage \
                --entrypoint="/neurodocker/startup.sh" \
                poldracklab/fitlins:latest \
                coverage run \
                --rcfile /src/fitlins/docker/multiproc.coveragerc \
                $CONDA_PREFIX/bin/fitlins /data/sourcedata /out dataset \
                -d /data -m /models/model-001_smdl.json -w /scratch \
                --participant-label 01 02 03 --space MNI152NLin2009cAsym \
                --n-cpus 2 --mem-gb 4 -vv
      - run:
          name: Run FitLins Database-file
          no_output_timeout: 2h
          command: |
            mkdir -p /tmp/ds003/work_dbf 
            chmod 777 /tmp/ds003/work_dbf /tmp/ds003/derivatives
            export CONDA_PREFIX=/opt/miniconda-latest/envs/neuro
            docker run --rm -v /tmp/data/ds003_fmriprep:/data \
                -v /tmp/ds003/derivatives:/out \
                -v /tmp/ds003/work_dbf:/scratch \
                -v /tmp/data/ds003_models:/models \
                -e COVERAGE_FILE=/scratch/.coverage.database-file \
                --entrypoint="/neurodocker/startup.sh" \
                poldracklab/fitlins:latest \
                coverage run \
                --rcfile /src/fitlins/docker/multiproc.coveragerc \
                $CONDA_PREFIX/bin/fitlins /data/sourcedata /out dataset \
                -d /data -m /models/model-001_smdl.json -w /scratch \
                --participant-label 01 02 03 --space MNI152NLin2009cAsym \
                --n-cpus 2 --database-path /out/pybidsdb -vv
      - run:
          name: Run FitLins Database-file_exists
          no_output_timeout: 2h
          command: |
            mkdir -p /tmp/ds003/work_dbf2 
            chmod 777 /tmp/ds003/work_dbf2 /tmp/ds003/derivatives
            export CONDA_PREFIX=/opt/miniconda-latest/envs/neuro
            docker run --rm -v /tmp/data/ds003_fmriprep:/data \
                -v /tmp/ds003/derivatives:/out \
                -v /tmp/ds003/work_dbf2:/scratch \
                -v /tmp/data/ds003_models:/models \
                -e COVERAGE_FILE=/scratch/.coverage.database-file \
                --entrypoint="/neurodocker/startup.sh" \
                poldracklab/fitlins:latest \
                coverage run \
                --rcfile /src/fitlins/docker/multiproc.coveragerc \
                $CONDA_PREFIX/bin/fitlins /data/sourcedata /out dataset \
                -d /data -m /models/model-001_smdl.json -w /scratch \
                --participant-label 01 02 03 --space MNI152NLin2009cAsym \
                --n-cpus 2 --database-path /out/pybidsdb -vv
      - store_artifacts:
          path: /tmp/ds003
      - persist_to_workspace:
          root: /tmp/ds003
          paths:
            - work/.coverage.*
            - work_dbf*/.coverage.*

  upload_coverage:
    machine:
      image: circleci/classic:201711-01
    working_directory: /tmp/src/fitlins
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Install coverage and codecov
          command: |
              pyenv install 3.6.3
              pyenv local 3.6.3
              python -m pip install -U "coverage<5" codecov
      - run:
          name: Combine coverage and submit
          command: |
              pyenv local 3.6.3
              python -m coverage combine \
                --rcfile /tmp/src/fitlins/docker/multiproc.coveragerc \
                /tmp/ds003/work/.coverage.* \
                /tmp/ds003/work_dbf*/.coverage.* \
                /tmp/pytestcov/.coverage*

              sed -i -e 's/\/src\/fitlins/\/tmp\/src\/fitlins/g' .coverage
              sed -i -e 's/.opt.miniconda-latest.envs.neuro.lib.python3.6.site-packages/\/tmp\/src\/fitlins/g' .coverage
              python -m coverage xml
              python -m codecov --file coverage.xml --flags circleci -e CIRCLE_JOB

  test_packaging:
    docker:
      - image: python:3.7.4
    working_directory: /tmp/src/fitlins
    steps:
      - run:
          name: Check Python version and upgrade pip
          command: |
            python --version
            python -m pip install -U pip setuptools virtualenv twine
      - checkout
      - run:
          name: Build FitLins
          command: |
            virtualenv --python=python /tmp/venv/build
            source /tmp/venv/build/bin/activate
            pip install --upgrade "pip>=19.1" setuptools wheel
            python setup.py sdist
            pip wheel --no-deps -w dist/ .
      - store_artifacts:
          path: /tmp/src/fitlins/dist
      - run:
          name: Check sdist distribution
          command: |
            THISVERSION=$( python -c 'import fitlins; print(fitlins.__version__)' )
            THISVERSION="${CIRCLE_TAG:-$THISVERSION}"
            twine check dist/fitlins*.tar.gz
            virtualenv --python=python /tmp/venv/sdist
            source /tmp/venv/sdist/bin/activate
            pip install --upgrade "pip>=19.1" setuptools wheel
            pip install dist/fitlins*.tar.gz
            which fitlins | grep sdist\\/bin
            INSTALLED_VERSION=$(fitlins --version)
            echo "VERSION: \"$THISVERSION\""
            echo "INSTALLED: \"$INSTALLED_VERSION\""
            test "$INSTALLED_VERSION" = "fitlins v$THISVERSION"
      - run:
          name: Check wheel distribution
          command: |
            THISVERSION=$( python -c 'import fitlins; print(fitlins.__version__)' )
            THISVERSION="${CIRCLE_TAG:-$THISVERSION}"
            twine check dist/fitlins*.whl
            virtualenv --python=python /tmp/venv/wheel
            source /tmp/venv/wheel/bin/activate
            pip install --upgrade "pip>=19.1" setuptools wheel
            pip install dist/fitlins*.whl
            which fitlins | grep wheel\\/bin
            INSTALLED_VERSION=$(fitlins --version)
            echo "VERSION: \"$THISVERSION\""
            echo "INSTALLED: \"$INSTALLED_VERSION\""
            test "$INSTALLED_VERSION" = "fitlins v$THISVERSION"

  deploy_pypi:
    docker:
      - image: python:3.7.4
    working_directory: /tmp/src/fitlins
    steps:
      - run:
          name: Check Python version and upgrade pip
          command: |
            python --version
            python -m pip install -U pip setuptools virtualenv twine
      - checkout
      - run:
          name: Build FitLins
          command: |
            virtualenv --python=python /tmp/venv/build
            source /tmp/venv/build/bin/activate
            pip install --upgrade "pip>=19.1" setuptools wheel
            python setup.py sdist
            pip wheel --no-deps -w dist/ .
      - store_artifacts:
          path: /tmp/src/fitlins/dist
      - run:
          name: Upload packages to PyPI
          command: |
            twine check dist/fitlins*
            twine upload dist/fitlins*

  deploy_master:
    machine:
      image: circleci/classic:201711-01
    working_directory: /tmp/src/fitlins
    steps:
      - restore_cache:
          keys:
            - docker-v0-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Load Docker image layer cache
          no_output_timeout: 30m
          command: |
            docker info
            set +o pipefail
            if [ -f /tmp/cache/docker.tar.gz ]; then
              zcat /tmp/cache/docker.tar.gz | docker load
              docker images
            fi
      - run:
          name: Deploy to Docker Hub
          no_output_timeout: 40m
          command: |
            if [[ -n "$DOCKER_PASS" ]]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker tag poldracklab/fitlins poldracklab/fitlins:master
              docker push poldracklab/fitlins:master
            fi

  deploy_docker:
    machine:
      image: circleci/classic:201711-01
    working_directory: /tmp/src/fitlins
    steps:
      - restore_cache:
          keys:
            - docker-v0-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Load Docker image layer cache
          no_output_timeout: 30m
          command: |
            docker info
            set +o pipefail
            if [ -f /tmp/cache/docker.tar.gz ]; then
              zcat /tmp/cache/docker.tar.gz | docker load
              docker images
            fi
      - run:
          name: Deploy to Docker Hub
          no_output_timeout: 40m
          command: |
            if [[ -n "$DOCKER_PASS" ]]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push poldracklab/fitlins:latest
              docker tag poldracklab/fitlins poldracklab/fitlins:$CIRCLE_TAG
              docker push poldracklab/fitlins:$CIRCLE_TAG
            fi

  deployable:
    docker:
      - image: busybox:latest
    steps:
      - run: echo Deploying!


workflows:
  version: 2
  fitlins_tests:
    jobs:
      - build:
          filters:
            branches:
              ignore: /doc\/.*/
            tags:
              only: /.*/
      - cache_test_data:
          filters:
            branches:
              ignore: /doc\/.*/
            tags:
              only: /.*/
      - build_docs:
          filters:
            tags:
              only: /.*/
      - test_pytest:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - test_ds003:
          requires:
            - build
            - cache_test_data
          filters:
            tags:
              only: /.*/
      - upload_coverage:
          requires:
            - test_pytest
            - test_ds003
          filters:
            tags:
              only: /.*/
      - test_packaging:
          filters:
            tags:
              only: /.*/
      - deploy_master:
          requires:
            - test_ds003
          filters:
            branches:
              only: master
      - deploy_docker:
          requires:
            - test_ds003
            - build_docs
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - deploy_pypi:
          requires:
            - test_ds003
            - build_docs
            - test_packaging
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
